# Generated by Django 3.2.25 on 2025-06-19 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.CharField(max_length=255)),
                ('your_full_name', models.CharField(max_length=255)),
                ('email_address', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=255)),
                ('your_sub_domain', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
