# Generated by Django 3.2.25 on 2025-07-18 12:21

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='date',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='facebook_profile_link',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='linkedin_Profile_link',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='select_employee_type',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='select_gender',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='teachers',
            name='contact_phone',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teachers',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teachers',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2025, 7, 18, 12, 11, 57, 466557, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teachers',
            name='employee_type',
            field=models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('CONTRACT', 'Contract')], default=datetime.datetime(2025, 7, 18, 12, 12, 36, 992996, tzinfo=utc), max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teachers',
            name='facebook_profile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teachers',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='teachers',
            name='linkedin_profile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teachers',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='teacher_profiles/'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='teachers',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='email',
            field=models.EmailField(default=datetime.datetime(2025, 7, 18, 12, 13, 14, 596863, tzinfo=utc), max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teachers',
            name='first_name',
            field=models.CharField(default=datetime.datetime(2025, 7, 18, 12, 14, 10, 67457, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teachers',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='profile_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='teacher_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
