# Generated by Django 5.2.4 on 2025-08-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_schedulecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeesAndInvoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_name', models.CharField(max_length=225)),
                ('fee_type', models.CharField(max_length=225)),
                ('invoice_date', models.CharField(max_length=225)),
                ('due_date', models.CharField(max_length=225)),
                ('description', models.TextField()),
                ('line_item', models.CharField(max_length=225)),
                ('item_desc', models.TextField()),
                ('settings', models.CharField(max_length=225)),
                ('partial_payments', models.BooleanField(default=False)),
                ('credit_balance', models.BooleanField(default=False)),
                ('link_with_finance', models.BooleanField(default=False)),
                ('multi_currency', models.BooleanField(default=False)),
            ],
        ),
    ]
