# Generated by Django 3.2.25 on 2025-07-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20250718_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='employee_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
