# Generated by Django 3.2.25 on 2025-06-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20250620_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(blank=True, max_length=255, null=True)),
                ('section_code', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
