# Generated by Django 5.2.4 on 2025-08-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_feesandinvoices'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManageOrgInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name', models.CharField(max_length=255)),
                ('institute_short_name', models.CharField(max_length=255)),
                ('sms_sender_id', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('phone_country_code', models.CharField(max_length=255)),
                ('post_code', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('id_bg_color', models.CharField(max_length=255)),
            ],
        ),
    ]
