# Generated by Django 3.2.25 on 2025-07-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20250718_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='addstudents',
            name='password',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
