# Generated by Django 3.2.25 on 2025-06-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(blank=True, max_length=255, null=True)),
                ('subject_code', models.CharField(blank=True, max_length=255, null=True)),
                ('subject_credit', models.CharField(blank=True, max_length=255, null=True)),
                ('subject_type', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
