# Generated by Django 3.2.25 on 2025-07-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_addstudents_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='password',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
