# Generated by Django 5.2.4 on 2025-08-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_manageorginfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terminology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students', models.CharField(max_length=255)),
                ('parents', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('credits_hours', models.CharField(max_length=255)),
                ('assessment', models.CharField(max_length=255)),
                ('grade_book', models.CharField(max_length=255)),
                ('section', models.CharField(max_length=255)),
                ('library', models.CharField(max_length=255)),
                ('review', models.CharField(max_length=255)),
                ('events', models.CharField(max_length=255)),
                ('incident', models.CharField(max_length=255)),
                ('social_learning', models.CharField(max_length=255)),
                ('teachers', models.CharField(max_length=255)),
                ('alumni', models.CharField(max_length=255)),
                ('class_name', models.CharField(max_length=255)),
                ('subjects', models.CharField(max_length=255)),
                ('core', models.CharField(max_length=255)),
                ('flexi_core', models.CharField(max_length=255)),
                ('rubric', models.CharField(max_length=255)),
                ('report_cards', models.CharField(max_length=255)),
                ('lecture', models.CharField(max_length=255)),
                ('books', models.CharField(max_length=255)),
                ('tasks', models.CharField(max_length=255)),
                ('class_schedule', models.CharField(max_length=255)),
                ('incident_name', models.CharField(max_length=255)),
            ],
        ),
    ]
