# Generated by Django 3.2.25 on 2025-06-23 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_teachers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachers',
            old_name='contact_name',
            new_name='contact_number',
        ),
        migrations.RenameField(
            model_name='teachers',
            old_name='facebookprofilelink',
            new_name='facebook_profile_link',
        ),
        migrations.RenameField(
            model_name='teachers',
            old_name='linkedinProfilelink',
            new_name='linkedin_Profile_link',
        ),
    ]
