# Generated by Django 3.2.25 on 2025-06-23 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20250623_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(blank=True, max_length=255, null=True)),
                ('books_author', models.CharField(blank=True, max_length=255, null=True)),
                ('books_isbn', models.CharField(blank=True, max_length=255, null=True)),
                ('books_price', models.CharField(blank=True, max_length=255, null=True)),
                ('stock', models.CharField(blank=True, max_length=255, null=True)),
                ('select_avaliability', models.CharField(blank=True, max_length=255, null=True)),
                ('days_limit_for_check_in', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
