# Generated by Django 3.2.25 on 2025-06-23 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_books'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='select_avaliability',
            new_name='select_availability',
        ),
    ]
